### ISSUE TITLE
Needs solution branch

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/Codealong-Creating-Columns#1]
Solution branch would be helpful for comparing official final rendered view since there is no mockup.jpg

**Comment by jongrover** [comment]
@sammarcus This code Along has a video counterpart, so a student or instructor can check the outcome at the end of the video or by checking the code for the code along immediately after this one. None of the code alongs have solution branches currently... I'm not opposed to adding them, just not sure I understand what purpose it would serve.
