### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by Shmuwol** [learn-co-curriculum/Codealong-Creating-Columns#3]
I believe in the video the instructor is using emmet shortcuts, maybe add a note and a link to emmet documentation.
:)

**Comment by jongrover** [comment]
Hmmm @Shmuwol this should be included in your environment when you installed the learn app no?

**Comment by Shmuwol** [comment]
I dont think it was, I had to install it myself.

Thanks for the amazing tutorials!
