### ISSUE TITLE
Can't submit lesson

### ISSUE THREAD

**Issue by sensei100** [learn-co-curriculum/Codealong-Creating-Columns#7]
When I try to submit my lesson I receive the following error message:

Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
Your code looks the same as the lesson's. Please make changes and then try submitting again.

**Comment by AnnJohn** [comment]
hi @sensei100 since this is a technical issue, could you file a bug report (if you hover over your profile pic in Learn, you'll see an option from a drop down menu to file a bug report). Also, you can use the Ask a Question feature and someone will get back to you right away there. Thanks!
