### ISSUE TITLE
Merging causes Learn to disconnect

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/Codealong-Creating-Columns#9]
In this lab and a few that came just before it, when I merge changes from the development branch into master, Learn disconnects. Any idea why? Feel free to lmk if you need more specific repro steps.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback.

We have updated the Learn IDE and believe your issue should be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

As always, thanks for contributing! 💙
